<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'KubAT\\PhpSimple\\HtmlDomParser' => array($vendorDir . '/kub-at/php-simple-html-dom-parser/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Caxy\\HtmlDiff' => array($vendorDir . '/caxy/php-htmldiff/lib'),
    'Camspiers' => array($vendorDir . '/camspiers/json-pretty/src'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
);
