<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phootwork\\lang\\' => array($vendorDir . '/phootwork/lang/src'),
    'phootwork\\collection\\' => array($vendorDir . '/phootwork/collection/src'),
    'gossi\\docblock\\' => array($vendorDir . '/gossi/docblock/src'),
    'Tuupola\\Middleware\\' => array($vendorDir . '/tuupola/cors-middleware/src'),
    'Symfony\\Polyfill\\Util\\' => array($vendorDir . '/symfony/polyfill-util'),
    'Symfony\\Polyfill\\Php56\\' => array($vendorDir . '/symfony/polyfill-php56'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Slim\\' => array($vendorDir . '/slim/slim/Slim'),
    'Seboettg\\Collection\\' => array($vendorDir . '/seboettg/collection/src/Seboettg/Collection'),
    'Seboettg\\CiteProc\\' => array($vendorDir . '/seboettg/citeproc-php/src'),
    'ScssPhp\\ScssPhp\\' => array($vendorDir . '/scssphp/scssphp/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'PhpXmlRpc\\' => array($vendorDir . '/phpxmlrpc/phpxmlrpc/src'),
    'ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'OTPHP\\' => array($vendorDir . '/spomky-labs/otphp/src'),
    'Neomerx\\JsonApi\\' => array($vendorDir . '/neomerx/json-api/src'),
    'Neomerx\\Cors\\' => array($vendorDir . '/neomerx/cors-psr7/src'),
    'MyCLabs\\Enum\\' => array($vendorDir . '/myclabs/php-enum/src'),
    'ILess\\' => array($vendorDir . '/mishal/iless/lib/ILess'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'FastRoute\\' => array($vendorDir . '/nikic/fast-route/src'),
    'Assert\\' => array($vendorDir . '/beberlei/assert/lib/Assert'),
    'Algo26\\IdnaConvert\\' => array($vendorDir . '/algo26-matthias/idna-convert/src'),
);
